<?php

namespace AcmeNewsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use AcmeNewsBundle\Entity\News;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function getAllNews($currentPage = 1)
	{
		$query = $this->createQueryBuilder('n')
			->where('n.isPublished = 1')
			->orderBy('n.publishedAt', 'DESC')
			->getQuery();

		$paginator = $this->paginate($query, $currentPage);

		return $paginator;
	}

	public function getLastNews($amount = News::NUM_ITEMS, $exclude = false)
	{
		$query = $this->createQueryBuilder('n')
			->orderBy('n.publishedAt', 'DESC')
			->setMaxResults($amount)
			->where('n.id != :exclude');
		
		if($exclude){
			$query = $query
				->where('n.id != :exclude')
				->setParameter('exclude', $exclude);
		}

		return $query->getQuery()->getResult();
	}

	public function paginate($dql, $page = 1, $limit = News::NUM_ITEMS)
	{
		$paginator = new Paginator($dql);

		$paginator->getQuery()
			->setFirstResult($limit * ($page - 1)) // Offset
			->setMaxResults($limit); // Limit

		return $paginator;
	}
}
